name = "cf-worker-shorturl"
main = "src/index.js"
compatibility_date = "2023-04-13"
node_compat = true

[[kv_namespaces]]
binding = "LINKS"
id = "7f0bf9809c464f51871b753cdda2c124"
[build]
command = "npm run build"
[vars]
USERNAME = "li2niu" # Change it
PASSWORD = "li2niu" # Change it
JWT_SECRET = "li2niu" # Change it
DEFAULT_PAGE = "https://li2niu.com" # Change it
RECORD_CLICKS = true

